steps:
  - id: "Set App Engine variables"
    name: "gcr.io/cloud-builders/gcloud"
    secretEnv: ["DB_URI", "SERVICE_ACCOUNT_EMAIL", "PIX_QRCODE_BUCKET_NAME", "CLIENT_ID", "CLIENT_SECRET", "PROJECT_ID"]
    entrypoint: "bash"
    args:
      - -c
      - |
        echo $'\n  DB_URI: '$$DB_URI >> ./infra/app_engine/${_ENV}.yaml
        echo $'\n  SERVICE_ACCOUNT_EMAIL: '$$SERVICE_ACCOUNT_EMAIL >> ./infra/app_engine/${_ENV}.yaml
        echo $'\n  PIX_QRCODE_BUCKET_NAME: '$$PIX_QRCODE_BUCKET_NAME >> ./infra/app_engine/${_ENV}.yaml
        echo $'\n  CLIENT_ID: '$$CLIENT_ID >> ./infra/app_engine/${_ENV}.yaml
        echo $'\n  CLIENT_SECRET: '$$CLIENT_SECRET >> ./infra/app_engine/${_ENV}.yaml
        echo $'\n  PROJECT_ID: '$$PROJECT_ID >> ./infra/app_engine/${_ENV}.yaml
        echo $'\n  SERVICE_NAME: ${_SERVICE_NAME}\n' >> ./infra/app_engine/${_ENV}.yaml
        echo $'\n  SERVICE_TAG: ${_SERVICE_TAG}\n' >> ./infra/app_engine/${_ENV}.yaml
    timeout: "1600s"

  - id: "Move App Engine env"
    name: "gcr.io/cloud-builders/gcloud"
    entrypoint: "bash"
    args: ["-c", "mv ./infra/app_engine/${_ENV}.yaml ./app.yaml"]
    timeout: "1600s"

  - id: "Deploy App Engine"
    name: "google/cloud-sdk"
    entrypoint: "bash"
    args:
      [
        "-c",
        "gcloud config set app/cloud_build_timeout 1600 && gcloud app deploy",
      ]
    timeout: "1600s"

availableSecrets:
  secretManager:
    - versionName: projects/$PROJECT_ID/secrets/PROJECT_ID/versions/latest
      env: "PROJECT_ID"
    - versionName: projects/$PROJECT_ID/secrets/SERVICE_ACCOUNT_EMAIL/versions/latest
      env: "SERVICE_ACCOUNT_EMAIL"
    - versionName: projects/$PROJECT_ID/secrets/${_ENV}_${_SERVICE_TAG}_DB_URI/versions/latest
      env: "DB_URI"
    - versionName: projects/$PROJECT_ID/secrets/${_ENV}_${_SERVICE_TAG}_PIX_QRCODE_BUCKET_NAME/versions/latest
      env: "PIX_QRCODE_BUCKET_NAME"
    - versionName: projects/$PROJECT_ID/secrets/${_ENV}_${_SERVICE_TAG}_CLIENT_ID/versions/latest
      env: "CLIENT_ID"
    - versionName: projects/$PROJECT_ID/secrets/${_ENV}_${_SERVICE_TAG}_CLIENT_SECRET/versions/latest
      env: "CLIENT_SECRET"
